[application]

# App (Project) Name
name = "Cobalt Installer"
default_platform = "desktop"

[bundle]
identifier = "com.divinedragonfanclub"
publisher = "Divine Dragon Fan Club"
icon = ["assets/SAMMIE.png"]

[web.app]

# HTML title tag content
title = "Cobalt Installer"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []